version: '2.1'
services:
  front:
    build: .
    image: nodejs
    container_name: front-conabio
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    command: ['npm','start']
  db:
    image: mdillon/postgis
    container_name: db-conabio
    hostname: db-hostname
    ports:
      - '5434:5432'
    volumes:
      - ./shapefiles:/shapefiles
      - ./sh-files:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: conabio
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
